[package]
edition.workspace = true
license.workspace = true
name              = "nats-examples"
version.workspace = true

[dependencies]
anyhow                           = "1.0"
nats-runtime-ext                 = { path = "../testing/integration" }
nats-runtime-workloads           = { path = "../testing/workloads" }
testing-framework-core           = { workspace = true }
testing-framework-runner-compose = { workspace = true }
tokio                            = { workspace = true, features = ["full"] }
tracing                          = { workspace = true }
tracing-subscriber               = { version = "0.3", features = ["env-filter"] }
which                            = "6.0"
