[package]
edition.workspace = true
license.workspace = true
name              = "metrics-counter-examples"
version.workspace = true

[dependencies]
anyhow                            = "1.0"
metrics-counter-node              = { path = "../metrics-counter-node" }
metrics-counter-runtime-ext       = { path = "../testing/integration" }
metrics-counter-runtime-workloads = { path = "../testing/workloads" }
reqwest                           = { workspace = true, features = ["json"] }
serde                             = { workspace = true }
serde_json                        = { workspace = true }
testing-framework-core            = { workspace = true }
testing-framework-runner-compose  = { workspace = true }
testing-framework-runner-k8s      = { workspace = true }

tokio              = { workspace = true, features = ["full"] }
tracing            = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
