[package]
edition.workspace = true
license.workspace = true
name              = "scheduler-runtime-workloads"
version.workspace = true

[dependencies]
async-trait            = { workspace = true }
scheduler-node         = { path = "../../scheduler-node" }
scheduler-runtime-ext  = { path = "../integration" }
serde                  = { workspace = true }
testing-framework-core = { workspace = true }
tokio                  = { workspace = true, features = ["full"] }
tracing                = { workspace = true }
