apiVersion: v1
kind: Service
metadata:
  name: {{ include "logos-runner.fullname" . }}-cfgsync
  labels:
    {{- include "logos-runner.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "logos-runner.selectorLabels" . | nindent 4 }}
    logos/component: cfgsync
  ports:
    - name: http
      port: {{ .Values.cfgsync.port }}
      targetPort: http
