# Config file reference can be found at https://embarkstudios.github.io/cargo-deny/checks/cfg.html.

[graph]
all-features        = true
exclude-dev         = true
no-default-features = true

[advisories]
ignore = ["RUSTSEC-2026-0097"]
yanked = "deny"

[bans]
allow-wildcard-paths = false
multiple-versions    = "allow"

[licenses]
allow = [
  "Apache-2.0 WITH LLVM-exception",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "ISC",
  "MIT",
  "Unicode-3.0",
  "Zlib",
]
private = { ignore = false }
unused-allowed-license = "deny"

[[licenses.clarify]]
expression    = "MIT AND ISC"
license-files = [{ hash = 0xbd0eed23, path = "LICENSE" }]
name          = "ring"

[[licenses.clarify]]
expression    = "MIT"
license-files = [{ hash = 0xcb90f5db, path = "LICENSE" }]
name          = "jsonpath-rust"

[sources]
allow-git        = []
unknown-git      = "deny"
unknown-registry = "deny"
