[package]
edition.workspace = true
license.workspace = true
name              = "scheduler-node"
version.workspace = true

[[bin]]
name = "scheduler-node"
path = "src/main.rs"

[dependencies]
anyhow             = "1.0"
axum               = "0.7"
clap               = { version = "4.0", features = ["derive"] }
reqwest            = { workspace = true, features = ["json"] }
serde              = { workspace = true }
serde_yaml         = { workspace = true }
tokio              = { workspace = true, features = ["full"] }
tower-http         = { version = "0.6", features = ["trace"] }
tracing            = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
