[package]
description = { workspace = true }
edition     = { workspace = true }
license     = { workspace = true }
name        = "lb-workloads"
version     = { workspace = true }

[lints]
workspace = true

[dependencies]
# Workspace crates
lb-ext                 = { workspace = true }
lb-framework           = { workspace = true }
testing-framework-core = { workspace = true }

# External
thiserror = { workspace = true }
tokio     = { features = ["time"], workspace = true }
