[package]
edition.workspace = true
license.workspace = true
name              = "openraft-kv-runtime-ext"
version.workspace = true

[dependencies]
async-trait                      = { workspace = true }
openraft-kv-node                 = { path = "../../openraft-kv-node" }
reqwest                          = { workspace = true }
testing-framework-core           = { workspace = true }
testing-framework-runner-compose = { workspace = true }
testing-framework-runner-k8s     = { workspace = true }
testing-framework-runner-local   = { workspace = true }
