[package]
edition.workspace = true
license.workspace = true
name              = "multi-app-e2e"
version.workspace = true

[dependencies]
async-trait                      = { workspace = true }
multi-app-fixture                = { path = "../fixture" }
testing-framework-app            = { workspace = true }
testing-framework-container      = { workspace = true }
testing-framework-core           = { workspace = true }
testing-framework-runner-compose = { workspace = true }
tokio                            = { workspace = true, features = ["full"] }
