[package]
edition.workspace = true
license.workspace = true
name              = "pubsub-examples"
version.workspace = true

[[bin]]
name = "pubsub_basic_ws_roundtrip"
path = "src/bin/basic_ws_roundtrip.rs"

[[bin]]
name = "pubsub_basic_ws_reconnect"
path = "src/bin/basic_ws_reconnect.rs"

[[bin]]
name = "pubsub_compose_ws_roundtrip"
path = "src/bin/compose_ws_roundtrip.rs"

[[bin]]
name = "pubsub_compose_ws_reconnect"
path = "src/bin/compose_ws_reconnect.rs"

[[bin]]
name = "pubsub_k8s_ws_roundtrip"
path = "src/bin/k8s_ws_roundtrip.rs"

[[bin]]
name = "pubsub_k8s_manual_ws_roundtrip"
path = "src/bin/k8s_manual_ws_roundtrip.rs"

[dependencies]
anyhow                           = "1.0"
pubsub-node                      = { path = "../pubsub-node" }
pubsub-runtime-ext               = { path = "../testing/integration" }
pubsub-runtime-workloads         = { path = "../testing/workloads" }
serde                            = { workspace = true }
testing-framework-core           = { workspace = true }
testing-framework-runner-compose = { workspace = true }
testing-framework-runner-k8s     = { workspace = true }
tokio                            = { workspace = true, features = ["full"] }
tracing                          = { workspace = true }
tracing-subscriber               = { version = "0.3", features = ["env-filter"] }
