[package]
categories.workspace  = true
description.workspace = true
edition.workspace     = true
keywords.workspace    = true
license.workspace     = true
name                  = "testing-framework-runner-k8s"
readme.workspace      = true
repository.workspace  = true
version               = "0.1.0"

[lints]
workspace = true

[dependencies]
anyhow                 = "1"
async-trait            = { workspace = true }
cfgsync-artifacts      = { workspace = true }
cfgsync-core           = { workspace = true }
k8s-openapi            = { features = ["latest"], version = "0.27" }
kube                   = { default-features = false, features = ["client", "runtime", "rustls-tls"], version = "3.1" }
reqwest                = { features = ["json"], workspace = true }
rustls                 = { default-features = false, features = ["ring"], version = "0.23" }
serde                  = { workspace = true }
serde_json             = { workspace = true }
serde_yaml             = { workspace = true }
tempfile               = { workspace = true }
testing-framework-core = { path = "../../core" }
thiserror              = { workspace = true }
tokio                  = { features = ["macros", "net", "process", "rt-multi-thread", "sync", "time"], workspace = true }
tokio-retry            = "0.3"
tracing                = { workspace = true }
url                    = { version = "2" }
