[package]
edition.workspace = true
license.workspace = true
name              = "queue-runtime-workloads"
version.workspace = true

[dependencies]
async-trait            = { workspace = true }
queue-node             = { path = "../../queue-node" }
queue-runtime-ext      = { path = "../integration" }
serde                  = { workspace = true }
testing-framework-core = { workspace = true }
tokio                  = { workspace = true, features = ["full"] }
tracing                = { workspace = true }
