[package]
edition.workspace = true
license.workspace = true
name              = "scheduler-runtime-ext"
version.workspace = true

[dependencies]
async-trait                      = { workspace = true }
scheduler-node                   = { path = "../../scheduler-node" }
serde                            = { workspace = true }
testing-framework-core           = { workspace = true }
testing-framework-runner-compose = { workspace = true }
testing-framework-runner-local   = { workspace = true }
