[package]
edition.workspace = true
license.workspace = true
name              = "openraft-kv-runtime-workloads"
version.workspace = true

[dependencies]
anyhow                  = "1.0"
async-trait             = { workspace = true }
openraft-kv-node        = { path = "../../openraft-kv-node" }
openraft-kv-runtime-ext = { path = "../integration" }
testing-framework-core  = { workspace = true }
thiserror               = "2.0"
tokio                   = { workspace = true, features = ["full"] }
tracing                 = { workspace = true }
