[package]
categories  = { workspace = true }
description = { workspace = true }
edition     = { workspace = true }
keywords    = { workspace = true }
license     = { workspace = true }
name        = "cfgsync-runtime"
readme      = { workspace = true }
repository  = { workspace = true }
version     = { workspace = true }

[lints]
workspace = true

[dependencies]
anyhow                 = "1"
cfgsync-core           = { workspace = true }
clap                   = { version = "4", features = ["derive"] }
serde                  = { workspace = true }
serde_yaml             = { workspace = true }
testing-framework-core = { workspace = true }
tokio                  = { default-features = false, features = ["macros", "net", "rt-multi-thread"], version = "1" }
